### ISSUE TITLE
[BUG] Song titles don't display when playing a radio station

### ISSUE THREAD

**Issue by doweaver** [ciderapp/Cider#86]
**Describe the bug**
If I play a live radio station, the song titles don't display as they're playing. On the native app, the title of the song appears alongside the radio station title.

**To Reproduce**
1. Go to 'Radio'
2. Click on any of the live Apple Music radio stations, such as 'Apple Music Hits'

**Expected behavior**
The title and artist of the currently playing song should be displayed, in addition to the radio station title.

**Screenshots**
![image](https://user-images.githubusercontent.com/235054/148442023-debf0917-1fc3-4d0f-b26d-3cc72cde0239.png)

**Environment Information**
 - OS: Windows 19043.1415
 - Application Version: 1.0
 ```
 version: 1.0.0
files:
  - url: Cider-Setup-1.0.0.exe
    sha512: Kdi7pVY4B7yfKIx9DGxDbYd0oabC3eWMiSblmbZZA8yqkapI7B1FN5l6ZwBJzEaszTcNTLAzqU8TNz5cAL/KCw==
    size: 70971680
path: Cider-Setup-1.0.0.exe
sha512: Kdi7pVY4B7yfKIx9DGxDbYd0oabC3eWMiSblmbZZA8yqkapI7B1FN5l6ZwBJzEaszTcNTLAzqU8TNz5cAL/KCw==
releaseDate: '2022-01-05T16:43:39.361Z'
```

**Have you followed the troubleshooting guide and checked for any outstanding/pinned issues that can help?**
*Troubleshooting guide can be found [here](https://github.com/Apple-Music-Electron/Apple-Music-Electron/wiki/Troubleshooting).*
Yes

**Log File**
[main.log](https://github.com/ciderapp/Cider/files/7824349/main.log)
